# CodeRabbit Configuration
# Documentation: https://docs.coderabbit.ai/config-file
#
# This file is kept minimal to comply with the schema.
# CodeRabbit will use default settings for code review.
# Refer to https://docs.coderabbit.ai/config-file for available options.

{}
